# Generated by Django 5.2.17 on 2026-09-22 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=20, unique=True)),
                ('modele', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['plaque'],
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('telephone', models.CharField(max_length=30)),
                ('courriel', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=255)),
                ('permis_numero', models.CharField(max_length=50)),
                ('permis_expiration', models.DateField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en-trajet', 'En trajet'), ('hors-service', 'Hors service')], default='disponible', max_length=20)),
                ('cree_le', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur', to=settings.AUTH_USER_MODEL)),
                ('plaque_habituelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeurs_habituels', to='flotte.vehicule')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('chauffeur', 'Chauffeur')], default='chauffeur', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('plaque', models.CharField(max_length=20)),
                ('depart', models.CharField(max_length=150)),
                ('depart_adresse', models.CharField(max_length=255)),
                ('arrivee', models.CharField(max_length=150)),
                ('debut', models.DateTimeField()),
                ('fin_prevue', models.DateTimeField()),
                ('fin', models.DateTimeField(null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en-cours', 'En cours'), ('termine', 'Terminé')], default='en-cours', max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='flotte.chauffeur')),
                ('vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajets', to='flotte.vehicule')),
            ],
            options={
                'ordering': ['-debut'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('technique', 'Technique'), ('route', 'Route')], default='route', max_length=20)),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('lieu', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('heure', models.CharField(help_text='Format HH:MM', max_length=5)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('traite', 'Traité')], default='ouvert', max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='flotte.chauffeur')),
                ('trajet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='flotte.trajet')),
            ],
            options={
                'ordering': ['-date', '-heure'],
            },
        ),
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=150)),
                ('heure', models.CharField(help_text='Format HH:MM', max_length=5)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='flotte.trajet')),
            ],
            options={
                'ordering': ['heure'],
            },
        ),
    ]
